import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/ui/SideBar";
import NavDetails from "../components/ui/NavDetails";
import Cursor from "@/components/ui/Cursor";
import Home from "./Home/page";
import About from "./(about)/page";
import Orders from "./Orders/page";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          animationDelay: `${0.05}`,
          animationDuration: "1s",
        }}
        className={`${geistSans.variable} ${geistMono.variable} size-full antialiased xl:flex`}
      >
        {/* <Cursor>
          <div className="relative flex size-full max-sm:flex-col">
            <SideBar />
            {children}
          </div>
        </Cursor> */}

        <Orders />
      </body>
    </html>
  );
}
